export const labelsGroupArr = {
	"Анализ крови": {
		"blood_group": "Группа крови",
		"RW_blood_1": "Кровь на RW",
		"registration_date": "Дата взятия на учет",
		"Rh_patient": "Резус-принадлежность беременной",
		"RW_blood_2": "Кровь на RW 2",
		"came_from": "Прибыла из другой мед. организации: ",
		"Rh_partner": "Резус-принадлежность мужа/партнера",
		"HIV_patient": "Кровь на ВИЧ",
		"from": "Указать откуда",
		"Rh_antibody_titer_28": "Титр резус-антител в 28 нед. беременности",
		"HIV_partner": "Кровь на ВИЧ партнерa",
	},
	"Данные о пациенте": {
		"last_name": "Фамилия",
		"name": "Имя",
		"patronymic": "Отчество",
		"date_of_birth": "Число, месяц, год рождения",
		"age": "Возраст",
		"patient_category": "Категория пациента",
		"insurance": "Территория страхования",
		"social_security_card_number": "Номер удостоверения соц. защиты",
		"phone": "Телефон",
		"citizenship": "Гражданство",
		"permanent_residence": "Постоянное место жительства",
	},
	"Трудовая деятельность и образование": {
		"work": "Место работы",
		"job_title": "Должность",
		"work_phone": "Рабочий телефон",
		"working_conditions": "Условия труда",
		"work_or_not": "Работает ли теперь",
		"education": "Образование",
		"marital_status": "Семейное положение",
		"holiday_from": "Дан отпуск по беременности с",
		"holiday_to": "Дан отпуск по беременности до",
		"last_name_partner": "Фамилия мужа",
		"work_partner": "Место работы мужа/партнера",
		"work_phone_partner": "Номер телефона мужа/партнера",
		"gestational_age_period": "Срок беременности по последним месячным",
		"gestational_age_ultrasound": "От УЗИ",
		"estimated_date_of_birth": "Предполагаемая дата родов",
		"pregnant_number": "Беременность (которая)",
		"childbirth_number": "Роды (которые)",
		"accounting_after_12_weeks": "Если взята на учет на сроке свыше 12нед.",
		"date_of_inspection": "Дата осмотра",
		"number_disability": "№ листка нетрудоспособности",
	},
	"Жалобы при первичном осмотре": {
		"complaints": "Жалобы при первичном осмотре",
		"drug_tolerance": "Аллергия на препараты",
		"diseases": "Перенесенные заболевания и операции",
	},
	"Первое обследование беременной": {
		"growth": "Рост",
		"weigth": "Вес",
		"skin": "Кожные покровы и слизистые",
		"thyroid": "Щитовидная железа:",
		"breast": "Молочные железы",
		"peripheral_lymph_nodes": "Периферические лимфатические узлы",
		"respiratory_system": "Дыхательная система",
		"cardiovascular_system": "Сердечно-сосудистая система",
		"blood_pressure": "Артериальное давление",
		"digestive_system": "Пищеварительная система:",
		"urinary_system": "Мочевыделительная система",
		"edema": "Отеки",
		"bone_pelvis": "Костный таз",
		"uterine_fundus_height": "Высота дна матки",
		"fetal_heartbeat": "Сердцебиение плода",
		"external_genitalia": "Наружные половые органы",
		"cervical_examination": "Осмотр шейки матки в зеркалах",
		"bimanual_study": "Бимануальное исследование",
		"vaginal_discharge": "Выделения из влагалища",
		"preliminary_diagnosis": "Предварительный диагноз",
	},
	"Назначения": {
		"blood_test_hemoglobin": "Анализ крови на гемоглобин",
		"blood_type_Rh_factor": "Группа крови и резус фактор",
		"urinalysis_protein": "Анализ мочи на белок",
		"pretest_HIV": "Проведено дотестовое консультирование по ВИЧ",
		"according_to_testing": "Согласно на тестирование",
		"HIV_blood_test": "Анализ крови на ВИЧ",
		"blood_test_syphilis": "Анализ крови на сифилис",
		"bacteriological_culture": "Бактериологический посев мочи",
		"ultrasound_18": "УЗИ (в 18 недель)",
		"folic_acid": "Фолиевая кислота",
		"potassium_iodide": "Калия йодид"
	}
}

export const labelsObj = {
	"blood_group": "Группа крови",
	"RW_blood_1": "Кровь на RW",
	"registration_date": "Дата взятия на учет",
	"Rh_patient": "Резус-принадлежность беременной",
	"RW_blood_2": "Кровь на RW 2",
	"came_from": "Прибыла из другой мед. организации: ",
	"Rh_partner": "Резус-принадлежность мужа/партнера",
	"HIV_patient": "Кровь на ВИЧ",
	"from": "Указать откуда",
	"Rh_antibody_titer_28": "Титр резус-антител в 28 нед. беременности",
	"HIV_partner": "Кровь на ВИЧ партнерa",
	"last_name": "Фамилия",
	"name": "Имя",
	"patronymic": "Отчество",
	"date_of_birth": "Число, месяц, год рождения",
	"age": "Возраст",
	"patient_category": "Категория пациента",
	"insurance": "Территория страхования",
	"social_security_card_number": "Номер удостоверения соц. защиты",
	"phone": "Телефон",
	"citizenship": "Гражданство",
	"permanent_residence": "Постоянное место жительства",
	"work": "Место работы",
	"job_title": "Должность",
	"work_phone": "Рабочий телефон",
	"working_conditions": "Условия труда",
	"work_or_not": "Работает ли теперь",
	"education": "Образование",
	"marital_status": "Семейное положение",
	"holiday_from": "Дан отпуск по беременности с",
	"holiday_to": "Дан отпуск по беременности до",
	"last_name_partner": "Фамилия мужа",
	"work_partner": "Место работы мужа/партнера",
	"work_phone_partner": "Номер телефона мужа/партнера",
	"gestational_age_period": "Срок беременности по последним месячным",
	"gestational_age_ultrasound": "От УЗИ",
	"estimated_date_of_birth": "Предполагаемая дата родов",
	"pregnant_number": "Беременность (которая)",
	"childbirth_number": "Роды (которые)",
	"accounting_after_12_weeks": "Если взята на учет на сроке свыше 12нед.",
	"date_of_inspection": "Дата осмотра",
	"number_disability": "№ листка нетрудоспособности",
	"complaints": "Жалобы при первичном осмотре",
	"drug_tolerance": "Аллергия на препараты",
	"diseases": "Перенесенные заболевания и операции",
	"growth": "Рост",
	"weigth": "Вес",
	"skin": "Кожные покровы и слизистые",
	"thyroid": "Щитовидная железа:",
	"breast": "Молочные железы",
	"peripheral_lymph_nodes": "Периферические лимфатические узлы",
	"respiratory_system": "Дыхательная система",
	"cardiovascular_system": "Сердечно-сосудистая система",
	"blood_pressure": "Артериальное давление",
	"digestive_system": "Пищеварительная система:",
	"urinary_system": "Мочевыделительная система",
	"edema": "Отеки",
	"bone_pelvis": "Костный таз",
	"uterine_fundus_height": "Высота дна матки",
	"fetal_heartbeat": "Сердцебиение плода",
	"external_genitalia": "Наружные половые органы",
	"cervical_examination": "Осмотр шейки матки в зеркалах",
	"bimanual_study": "Бимануальное исследование",
	"vaginal_discharge": "Выделения из влагалища",
	"preliminary_diagnosis": "Предварительный диагноз",
	"blood_test_hemoglobin": "Анализ крови на гемоглобин",
	"blood_type_Rh_factor": "Группа крови и резус фактор",
	"urinalysis_protein": "Анализ мочи на белок",
	"pretest_HIV": "Проведено дотестовое консультирование по ВИЧ",
	"according_to_testing": "Согласно на тестирование",
	"HIV_blood_test": "Анализ крови на ВИЧ",
	"blood_test_syphilis": "Анализ крови на сифилис",
	"bacteriological_culture": "Бактериологический посев мочи",
	"ultrasound_18": "УЗИ (в 18 недель)",
	"folic_acid": "Фолиевая кислота",
		"potassium_iodide": "Калия йодид"
}